# Generated by Django 2.1.7 on 2019-03-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvidha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='flight_good_cond',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='gross_weight',
            field=models.IntegerField(),
        ),
    ]
