# Generated by Django 2.1.7 on 2019-03-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvidha', '0002_auto_20190307_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='flight_good_cond',
            new_name='flight_good_condition',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='remark',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='harness_length',
            field=models.IntegerField(),
        ),
    ]
