# Generated by Django 2.1.7 on 2019-03-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvidha', '0003_auto_20190307_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='airport',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='arr_airport',
            field=models.CharField(default='BLR', max_length=150),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='arr_date',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='dep_airport',
            field=models.CharField(default='DEL', max_length=150),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='dep_date',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='halt_airport',
            field=models.CharField(default='NULL', max_length=150),
        ),
    ]
